type Person {
  id: Int!,
  name: String!,
  spouse: Person @relationship(type: "SPOUSE", direction: OUT),
  children: [Person!]! @relationship(type: "CHILD", direction: OUT),
  friends: [Person!]! @relationship(type: "FRIEND", direction: OUT),
  acquaintances: [Person!]! @relationship(type: "ACQUAINTANCE", direction: OUT),
  works: Company @relationship(type: "WORKS", direction: OUT)
}

type Company {
  id: Int!,
  name: String,
  employees: [Person!]! @relationship(type: "WORKS", direction: IN)
}

type Query {
  colleagues(id: Int!): [Person] @cypher(statement: "MATCH (:Person {id: $id})-[:WORKS]->()<-[:WORKS]-(p) RETURN p")
}

type Mutation {
  createChild(parent1id: Int!, parent2id: Int!, id: Int!, name: String!): Person 
  @cypher(statement: "MATCH (parent1: Person {id: $parent1id}), (parent2: Person {id: $parent2id}) MERGE (parent1)-[:CHILD]->(c:Person {id: $id, name: $name})<-[:CHILD]-(parent2) RETURN c")
}
